# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-04-18 15:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': '\u8bfe\u7a0b\u6559\u5e08', 'verbose_name_plural': '\u8bfe\u7a0b\u6559\u5e08'},
        ),
    ]
