# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-06-04 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_auto_20180517_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='teacher_org',
            field=models.ManyToManyField(blank=True, null=True, to='organization.CourseOrg', verbose_name='\u6559\u5e08\u6240\u5c5e\u673a\u6784'),
        ),
    ]
