# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-06-04 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_teacher_teacher_org'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='teacher_photo',
            field=models.ImageField(blank=True, null=True, upload_to='teacher/%Y/%m', verbose_name='\u6559\u5e08\u7167\u7247'),
        ),
    ]
