# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-06-27 13:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_teacher_teacher_photo'),
        ('course', '0004_auto_20180627_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='need_know',
            field=models.CharField(default='xxx', max_length=300, verbose_name='\u8bfe\u7a0b\u987b\u77e5'),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.Teacher', verbose_name='\u6388\u8bfe\u8001\u5e08'),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher_will_tell',
            field=models.CharField(default='xxx', max_length=300, verbose_name='\u8001\u5e08\u5c06\u544a\u8bc9\u4f60'),
        ),
    ]
