# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-05-29 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0002_auto_20180529_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userask',
            name='course_name',
            field=models.CharField(default='python', max_length=50, verbose_name='\u8bfe\u7a0b\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='userask',
            name='mobile',
            field=models.CharField(default='13554494531', max_length=11, verbose_name='\u624b\u673a\u53f7'),
        ),
        migrations.AlterField(
            model_name='userask',
            name='name',
            field=models.CharField(default='yushengzhou', max_length=20, verbose_name='\u540d\u5b57'),
        ),
    ]
